export const NYC_NEIGHBORHOODS: Record<string, string[]> = {
  manhattan: [
    'marble_hill', 'inwood', 'fort_george', 'washington_heights', 'hudson_heights',
    'west_harlem', 'hamilton_heights', 'manhattanville', 'morningside_heights',
    'central_harlem', 'east_harlem', 'upper_east_side', 'lenox_hill', 'carnegie_hill',
    'yorkville', 'upper_west_side', 'lincoln_square', 'sutton_place', 'midtown_east',
    'midtown', 'times_square', 'hells_kitchen', 'hudson_yards', 'midtown_west',
    'garment_district', 'murray_hill', 'chelsea', 'flatiron_district', 'gramercy_park',
    'union_square', 'meatpacking_district', 'alphabet_city', 'east_village',
    'greenwich_village', 'noho', 'west_village', 'lower_east_side', 'soho', 'nolita',
    'little_italy', 'chinatown', 'financial_district', 'tribeca', 'battery_park_city',
    'hudson_square', 'roosevelt_island', 'nomad', 'koreatown', 'theater_district',
    'kips_bay', 'stuyvesant_town', 'peter_cooper_village', 'two_bridges', 'bowery',
    'civic_center', 'south_street_seaport', 'rockefeller_center', 'tudor_city',
    'waterside_plaza', 'herald_square', 'madison_square', 'flower_district',
    'diamond_district', 'sugar_hill', 'strivers_row',
  ],
  brooklyn: [
    'williamsburg', 'east_williamsburg', 'south_williamsburg', 'bushwick',
    'greenpoint', 'bed_stuy', 'crown_heights', 'flatbush', 'ditmas_park',
    'east_flatbush', 'prospect_lefferts_gardens', 'prospect_park_south',
    'windsor_terrace', 'kensington', 'brownsville', 'canarsie', 'east_new_york',
    'cypress_hills', 'new_lots', 'ocean_hill', 'stuyvesant_heights', 'wyckoff_heights',
    'brooklyn_heights', 'clinton_hill', 'downtown_brooklyn', 'dumbo', 'fort_greene',
    'prospect_heights', 'vinegar_hill', 'boerum_hill', 'carroll_gardens',
    'cobble_hill', 'gowanus', 'park_slope', 'south_park_slope', 'greenwood_heights',
    'red_hook', 'coney_island', 'brighton_beach', 'manhattan_beach', 'sheepshead_bay',
    'midwood', 'flatlands', 'gravesend', 'marine_park', 'mill_basin', 'bay_ridge',
    'fort_hamilton', 'bensonhurst', 'bath_beach', 'borough_park', 'dyker_heights',
    'sunset_park', 'remsen_village', 'gerritsen_beach', 'bergen_beach',
    'columbia_street_waterfront_district', 'fulton_ferry', 'sea_gate',
  ],
  queens: [
    'astoria', 'long_island_city', 'hunters_point', 'sunnyside', 'woodside',
    'jackson_heights', 'elmhurst', 'corona', 'forest_hills', 'rego_park',
    'ridgewood', 'glendale', 'maspeth', 'middle_village', 'flushing',
    'fresh_meadows', 'hillcrest', 'jamaica', 'south_jamaica', 'hollis',
    'st_albans', 'laurelton', 'queens_village', 'rosedale', 'springfield_gardens',
    'far_rockaway', 'rockaway_beach', 'rockaway_park', 'arverne', 'bayside',
    'college_point', 'douglaston', 'little_neck', 'whitestone', 'fresh_pond',
    'ozone_park', 'south_ozone_park', 'richmond_hill', 'woodhaven', 'howard_beach',
    'east_elmhurst', 'kew_gardens', 'briarwood', 'jamaica_estates', 'bellerose',
    'glen_oaks', 'cambria_heights', 'broad_channel', 'breezy_point',
    'north_corona', 'murray_hill_flushing', 'willets_point', 'ditmars',
  ],
  bronx: [
    'mott_haven', 'port_morris', 'melrose', 'morrisania', 'longwood',
    'hunts_point', 'tremont', 'east_tremont', 'west_farms', 'highbridge',
    'concourse', 'claremont', 'bathgate', 'belmont', 'fordham', 'norwood',
    'bedford_park', 'university_heights', 'morris_heights', 'kingsbridge',
    'riverdale', 'spuyten_duyvil', 'woodlawn', 'wakefield', 'williamsbridge',
    'baychester', 'co_op_city', 'pelham_bay', 'pelham_gardens', 'pelham_parkway',
    'city_island', 'throgs_neck', 'soundview', 'castle_hill', 'parkchester',
    'morris_park', 'van_nest', 'westchester_square', 'allerton', 'bronxdale',
    'edenwald', 'schuylerville', 'jerome_park', 'the_hub',
  ],
  staten_island: [
    'saint_george', 'tompkinsville', 'stapleton', 'clifton', 'rosebank',
    'new_brighton', 'west_new_brighton', 'port_richmond', 'mariners_harbor',
    'elm_park', 'richmond_valley', 'tottenville', 'pleasant_plains',
    'great_kills', 'new_dorp', 'midland_beach', 'south_beach', 'arrochar',
    'grasmere', 'concord', 'dongan_hills', 'oakwood', 'richmondtown',
    'castleton_corners', 'meiers_corners', 'heartland_village', 'new_springville',
    'bulls_head', 'bloomfield', 'charleston', 'woodrow', 'annadale',
    'arden_heights', 'huguenot', 'princes_bay', 'rossville', 'travis',
    'livingston', 'grymes_hill', 'emerson_hill', 'todt_hill', 'lighthouse_hill',
    'silver_lake', 'park_hill', 'westerleigh', 'manor_heights', 'graniteville',
  ],
  jersey: [
    'hoboken',
    'jersey_city',
  ],
}

export const ALL_NEIGHBORHOODS: { neighborhood: string; borough: string }[] =
  Object.entries(NYC_NEIGHBORHOODS).flatMap(([borough, neighborhoods]) =>
    neighborhoods.map(neighborhood => ({ neighborhood, borough }))
  )
